// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
	"github.com/sqlc-dev/pqtype"
)

// 购物车
type Cart struct {
	ID        int64           `json:"id"`
	UserID    int64           `json:"user_id"`
	SkuID     int64           `json:"sku_id"`
	Quantity  int32           `json:"quantity"`
	Price     decimal.Decimal `json:"price"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// 订单
type Order struct {
	ID          int64           `json:"id"`
	OrderNo     string          `json:"order_no"`
	UserID      int32           `json:"user_id"`
	Status      int16           `json:"status"`
	TotalAmount decimal.Decimal `json:"total_amount"`
	PaidAt      sql.NullTime    `json:"paid_at"`
	ExpireAt    sql.NullTime    `json:"expire_at"`
	CreatedAt   time.Time       `json:"created_at"`
}

// 订单项目
type OrderItem struct {
	ID        int64           `json:"id"`
	OrderID   int32           `json:"order_id"`
	ProductID int32           `json:"product_id"`
	Quantity  int32           `json:"quantity"`
	UnitPrice decimal.Decimal `json:"unit_price"`
}

// 商品
type Product struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Price       decimal.Decimal `json:"price"`
	Images      sql.NullString  `json:"images"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	DeletedAt   sql.NullTime    `json:"deleted_at"`
}

// 商品SKU
type ProductSku struct {
	ID        int64                 `json:"id"`
	ProductID int32                 `json:"product_id"`
	Name      string                `json:"name"`
	Specs     pqtype.NullRawMessage `json:"specs"`
	Price     decimal.Decimal       `json:"price"`
	Images    sql.NullString        `json:"images"`
	CreatedAt time.Time             `json:"created_at"`
	UpdatedAt time.Time             `json:"updated_at"`
	DeletedAt sql.NullTime          `json:"deleted_at"`
}

// 库存
type ProductSkuStock struct {
	SkuID int32 `json:"sku_id"`
	Stock int32 `json:"stock"`
}

// 用户
type User struct {
	ID        int64          `json:"id"`
	Phone     string         `json:"phone"`
	Email     sql.NullString `json:"email"`
	Username  string         `json:"username"`
	Password  string         `json:"password"`
	Avatar    string         `json:"avatar"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}

// 用户账户
type UserAccount struct {
	ID            int64           `json:"id"`
	UserID        int64           `json:"user_id"`
	FrozenBalance decimal.Decimal `json:"frozen_balance"`
	Balance       decimal.Decimal `json:"balance"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
	DeletedAt     sql.NullTime    `json:"deleted_at"`
}
