// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_account.sql

package model

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO user_account (user_id, frozen_balance, balance)
VALUES ($1, $2, $3)
    RETURNING id, user_id, frozen_balance, balance, created_at, updated_at, deleted_at
`

type CreateAccountParams struct {
	UserID        int64  `json:"user_id"`
	FrozenBalance string `json:"frozen_balance"`
	Balance       string `json:"balance"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (UserAccount, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.UserID, arg.FrozenBalance, arg.Balance)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FrozenBalance,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
