// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"log"
	"study/db/model"
	"study/internal/api/handler"
	"study/internal/app"
	"study/internal/domain/user"
	"study/internal/infra/repository"
	"study/token"
	"study/util"
	"study/util/errors"
	"study/util/i18n"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeDependencies(cfg util.Config) (*Dependencies, error) {
	txManager, err := NewDB(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(txManager)
	userAccountRepository := repository.NewUserAccountRepository(txManager)
	domainService := user.NewDomainService(userRepository, userAccountRepository)
	maker, err := NewTokenMaker(cfg)
	if err != nil {
		return nil, err
	}
	userService := app.NewUserService(domainService, txManager, maker)
	errorHandler := NewErrorHandler()
	translationService := NewTranslationService()
	userHandler := handler.NewUserHandler(userService, errorHandler, translationService)
	dependencies := &Dependencies{
		UserHandler: userHandler,
	}
	return dependencies, nil
}

// wire.go:

type Dependencies struct {
	UserHandler *handler.UserHandler
}

func NewDB(cfg util.Config) (model.TxManager, error) {
	db, err := sql.Open("postgres", cfg.DBSource)
	if err != nil {
		return nil, err
	}
	return model.NewStore(db), nil
}

func NewTokenMaker(cfg util.Config) (token.Maker, error) {
	return token.NewPasetoMaker(cfg.TokenSymmetricKey)
}

func NewErrorHandler() *errors.ErrorHandler {
	return errors.NewErrorHandler(true, false)
}

func NewTranslationService() *i18n.TranslationService {
	translator := i18n.NewFileTranslator("en")

	if err := translator.LoadTranslations("./config/i18n"); err != nil {
		log.Fatal(err)
	}
	return i18n.NewTranslationService(translator, "zh")
}
