CREATE TABLE "public"."user" (
                                 "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "phone" VARCHAR NOT NULL UNIQUE,
                                 "email" VARCHAR NULL UNIQUE,
                                 "username" VARCHAR NOT NULL UNIQUE,
                                 "password" VARCHAR NOT NULL,
                                 "avatar" VARCHAR NOT NULL DEFAULT '',
                                 "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                                 "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                                 "deleted_at" TIMESTAMPTZ
);

-- 重新创建唯一索引，防止重复
CREATE UNIQUE INDEX "idx_phone" ON "public"."user" ("phone");
CREATE UNIQUE INDEX "idx_email" ON "public"."user" ("email");

COMMENT ON TABLE "user" IS '用户';


CREATE TABLE "public"."user_account" (
                                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         "user_id" BIGINT NOT NULL UNIQUE,
                                         "frozen_balance" NUMERIC(10, 2) NOT NULL DEFAULT 0,
                                         "balance" NUMERIC(10, 2) NOT NULL DEFAULT 0,
                                         "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                                         "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                                         "deleted_at" TIMESTAMPTZ
);

-- 重新创建唯一索引，防止重复
CREATE INDEX "idx_user_id" ON "public"."user_account" ("user_id");

COMMENT ON TABLE user_account IS '用户账户';

