CREATE TABLE product (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name TEXT NOT NULL,
                         description TEXT,
                         price NUMERIC(10, 2) NOT NULL,
                         images TEXT,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE product IS '商品';

CREATE TABLE product_sku (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         product_id INTEGER NOT NULL,
                         name TEXT NOT NULL,
                         specs JSONB,   -- {"color": "black", "size": "M"}
                         price NUMERIC(10, 2) NOT NULL,
                         images TEXT,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE product_sku IS '商品SKU';

CREATE TABLE product_sku_stock (
                           sku_id INTEGER PRIMARY KEY,
                           stock INTEGER NOT NULL CHECK (stock >= 0)
);

CREATE INDEX "idx_product_sku_id" ON "public"."product_sku_stock" ("sku_id");
COMMENT ON TABLE product_sku_stock IS '库存';



CREATE TABLE "order" (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         order_no VARCHAR(30) NOT NULL,
                         user_id INTEGER NOT NULL,
                         status smallint NOT NULL DEFAULT 0,
                         total_amount NUMERIC(10, 2) NOT NULL,
                         paid_at TIMESTAMP,
                         expire_at TIMESTAMP,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX "idx_order_order_no" ON "public"."order" ("order_no");
CREATE INDEX "idx_order_user_id" ON "public"."order" ("user_id");
COMMENT ON TABLE "order" IS '订单';


CREATE TABLE order_item (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            order_id INTEGER NOT NULL,
                            product_id INTEGER NOT NULL,
                            quantity INTEGER NOT NULL CHECK (quantity > 0),
                            unit_price NUMERIC(10, 2) NOT NULL
);

CREATE INDEX "idx_order_items_order_id" ON "public"."order_item" ("order_id");
CREATE INDEX "idx_order_items_product_id" ON "public"."order_item" ("product_id");
COMMENT ON TABLE order_item IS '订单项目';