DROP TABLE IF EXISTS hotel CASCADE;
DROP TABLE IF EXISTS hotel_room_type CASCADE;
DROP TABLE IF EXISTS hotel_room_item CASCADE;
DROP TABLE IF EXISTS hotel_room_date CASCADE;
DROP TABLE IF EXISTS hotel_sku CASCADE;
DROP TABLE IF EXISTS hotel_sku_day_price CASCADE;
