CREATE TABLE "order" (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_sn VARCHAR(50) NOT NULL UNIQUE,
                        user_id BIGINT NOT NULL,
                        hotel_id BIGINT NOT NULL,
                        merchant_id BIGINT NOT NULL,
                        total_price DECIMAL(10,2) NOT NULL,
                        total_number INT NOT NULL,
                        total_pay_ticket INT NOT NULL,
                        status SMALLINT NOT NULL DEFAULT 0, -- e.g., 0=init, 1=confirmed, 2=cancelled
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        expire_time TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE order_room (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             room_type_id BIGINT NOT NULL,
                             room_item_id BIGINT NOT NULL,
                             price DECIMAL(10,2) NOT NULL,
                             status SMALLINT NOT NULL DEFAULT 0, -- e.g., 0=init, 1=confirmed, 2=cancelled
                             created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_order_user_id ON "order" ("user_id");
CREATE INDEX idx_order_room_order_id ON "order_room" ("order_id");