CREATE TABLE user_plan (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            order_id BIGINT NOT NULL,
                            room_item_id BIGINT NOT NULL,
                            phone VARCHAR(20) NOT NULL,
                            name VARCHAR(50) NOT NULL,
                            start_date TIMESTAMP WITH TIME ZONE NOT NULL,
                            end_date TIMESTAMP WITH TIME ZONE NOT NULL,
                            status SMALLINT NOT NULL DEFAULT 0,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_user_plans_phone_dates ON user_plan (phone, start_date, end_date);