CREATE TABLE "public"."user" (
                                  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "phone" VARCHAR NOT NULL UNIQUE,
                                  "email" VARCHAR NOT NULL UNIQUE,
                                  "username" VARCHAR NOT NULL UNIQUE,
                                  "password" VARCHAR NOT NULL,
                                  "avatar" VARCHAR NOT NULL DEFAULT '',
                                  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                                  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
                                  "deleted_at" TIMESTAMPTZ
);

-- 重新创建唯一索引，防止重复
CREATE UNIQUE INDEX "idx_phone" ON "public"."user" ("phone");
CREATE UNIQUE INDEX "idx_email" ON "public"."user" ("email");
CREATE UNIQUE INDEX "idx_username" ON "public"."user" ("username");
